### ISSUE TITLE
关于资源加载服务器问题

### ISSUE THREAD

**Issue by RoFatNya** [iamapig120/majsoul-plus-client#4]
这个mod是不是能让资源加载和游戏中数据交换分离开来？

**Comment by iamapig120** [comment]
勉强算是吧
Mod的话其实就是程序会拦截原有游戏的数据请求，然后按照以下顺序找文件用于返回
Mods=>本地缓存=>游戏服务器
所以说是Mod，但实际上理解为原有资源的重载会更好理解一些？
