### ISSUE TITLE
使用疑问

### ISSUE THREAD

**Issue by RoFatNya** [iamapig120/majsoul-plus-client#5]
这个东西能不能塞到linux_64服务器上，这样就可以用云服务器做代理来更改了，还有一点就是有没有使用教程啥的。

**Comment by iamapig120** [comment]
能塞到linux_64服务器上，但是会有个问题……https签名是不合法的……此外会无法实现代码注入
使用教程的话会在晚一些首先完善好UI之后，写一个使用教程的，嗯

**Comment by RoFatNya** [comment]
@iamapig120 这个签名是自签名的证书吗

**Comment by iamapig120** [comment]
> @iamapig120 这个签名是自签名的证书吗

是的，这货是一个自签名证书，有效期似乎有30多年，Electron里面我设置禁用了证书验证。

**Comment by iamapig120** [comment]
在README.md中添加了基本的说明

**Comment by iamapig120** [comment]
新GUI已基本完成，请下载新版本，并参照README.md制作插件、模组等。
欢迎分享、贡献代码以及制作好的插件模组。
